### ISSUE TITLE
the bouncing effect still exist

### ISSUE THREAD

**Issue by bau720123** [vilic/cordova-plugin-fix-wp-bouncing#1]
hi @vilic 
I am using PGB 3.7
I tried many times
but the bouncing effect still exist

```
<div id="mytest">
<p>1</p>
<p>2</p>
<p>3</p>
<p>4</p>
<p>5</p>
<p>6</p>
<p>7</p>
<p>8</p>
<p>9</p>
<p>10</p>
<p>11</p>
<p>12</p>
<p>13</p>
<p>14</p>
<p>15</p>
<p>16</p>
<p>17</p>
<p>18</p>
<p>19</p>
<p>20</p>
</div>
<script type="text/javascript">
var wrapper = document.getElementById("mytest");
FixWPBouncing.fix(wrapper);
</script>
```

**Comment by vilicvane** [comment]
have you added `-ms-touch-action: none;`  ?

**Comment by vilicvane** [comment]
and you should fix the element that scrolls, here not your div#mytest but body.

**Comment by vilicvane** [comment]
and by the way you should probably do that after `deviceready`.

**Comment by vilicvane** [comment]
I made some updates including README.md, please check out and see if it solves your issue.

**Comment by bau720123** [comment]
hi @vilic 
thanks for your reply
but it seem still fully work
these my code

```
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>testpage</title>
<style>
html {
    -ms-touch-action: none;
    touch-action: none;
}

#an-element-that-scrolls {
    height: 400px;
    overflow-y: auto;
}
</style>
</head>

<body>

<div id="mytest">
<p>1</p>
<p>2</p>
<p>3</p>
<p>4</p>
<p>5</p>
<p>6</p>
<p>7</p>
<p>8</p>
<p>9</p>
<p>10</p>
<p>11</p>
<p>12</p>
<p>13</p>
<p>14</p>
<p>15</p>
<p>16</p>
<p>17</p>
<p>18</p>
<p>19</p>
<p>20</p>
</div>

<script type="text/javascript">
document.addEventListener("deviceready", startEvents, false);
function startEvents()
{
alert(device.cordova) //I am very sure that phonegap version alert success
var wrapper = document.getElementById("mytest");
FixWPBouncing.fix(wrapper);
}

</body>
</html>
```

**Comment by vilicvane** [comment]
hmm, do you mean it works or not?

**Comment by bau720123** [comment]
hi @vilic 
the css code will helping not bouncing "too much"
but the bouncing effect still exist...(so this is what I mean "not fully work")
could you give me your "full sample" that help me test it...

**Comment by vilicvane** [comment]
you missed a `not` in your previous reply lol...

I delete my test sample just now... what a...

you code seems to be fine, except that element `p` has preset margin, you may want to override that (I'm not sure whether that would influence the result, maybe not).

and I've also updated the plugin itself, have you tried to remove and add it again?

**Comment by bau720123** [comment]
hi @vilic 
I tried many times in new version 0.1.1
but...still not work
could you give me your full sample code (I mean full sample project)

**Comment by vilicvane** [comment]
I took a closer look to your code and found some errors, here's the updated `index.html` that has been tested.

another change I've made to a newly created cordova project is to add `<preference name="fullscreen" value="true" />` to `config.xml`.

``` html
<!doctype html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi" />
    <title>testpage</title>
    <style>
        html {
            -ms-touch-action: none;
            touch-action: none;
        }

        #mytest {
            height: 400px;
            overflow-y: auto;
            background-color: #ccc;
        }
    </style>
</head>
<body>
    <div id="mytest">
        <p>1</p>
        <p>2</p>
        <p>3</p>
        <p>4</p>
        <p>5</p>
        <p>6</p>
        <p>7</p>
        <p>8</p>
        <p>9</p>
        <p>10</p>
        <p>11</p>
        <p>12</p>
        <p>13</p>
        <p>14</p>
        <p>15</p>
        <p>16</p>
        <p>17</p>
        <p>18</p>
        <p>19</p>
        <p>20</p>
    </div>
    <script src="cordova.js"></script>
    <script type="text/javascript">
        document.addEventListener("deviceready", function () {
            alert('~');
            var wrapper = document.getElementById("mytest");
            FixWPBouncing.fix(wrapper);
        }, false);
    </script>
</body>
</html>
```

**Comment by bau720123** [comment]
hi @vilic 
test OK !!!
but...if you change the css height to 100%
it will still bounce again

**Comment by vilicvane** [comment]
you may need to add height 100% to both body and html element. also, be sure to set margin 0 for body.

Sent from my Lumia 930
